### ISSUE TITLE
No-Code-Changes Instrumentation

### ISSUE THREAD

**Issue by basepi** [elastic/apm-agent-python#1600]
This is the meta issue for no-code-changes instrumentation.

- [ ] [Wrapper Script](https://github.com/elastic/apm-agent-python/issues/1019)
- [ ] [Django](https://github.com/elastic/apm-agent-python/issues/1597)
- [ ] [Flask](https://github.com/elastic/apm-agent-python/issues/1598)
- [ ] [aiohttp](https://github.com/elastic/apm-agent-python/issues/1599)
- [ ]
