### ISSUE TITLE
Plan for next milestone release: drop python 3.6 and 3.7 support

### ISSUE THREAD

**Issue by xrmx** [elastic/apm-agent-python#2029]
We want to remove support for python versions not supported upstream anymore, that is 3.6 and 3.7. That would simplify the code and our test matrix. 
We are waiting for 30th June 2024 to have RHEL 7 going end of support and benefit from people bumping to newer environments. 
Will also use this milestone bump in order to remove some deprecated code that currently raises a PendingDeprecationWarning.
So first will do a release moving code from PendingDeprecationWarning to DeprecationWarning in order to make it clear that the code is gonna go.
We plan the release with a bump milestone around July 2024.

7.0.0 removals:

- [ ] Python 3.6 support
- [ ] Python 3.7 support
- [ ] opentracing bridge
- [ ] logging handler
- [ ] django logging handler integration
- [ ] flask logging handler integration
- [ ] cleanup docs references to asyncio 3.7+, logging handlers and supported python versions

**Comment by xrmx** [comment]
We are going to drop Python 3.6 support in the next minor instead.
