### ISSUE TITLE
Add support to asyncio — Asynchronous I/O

### ISSUE THREAD

**Issue by lreuven** [elastic/apm-agent-python#598]
Add support to asyncio — Asynchronous I/O

- [x] Move blocking code to background thread (#607)
- [x] Add async `capture_span` variant (#657)
- [x] Add support for aiohttp client/web (#659)
- [x] Add support for tornado (#661)
- [x] Investigate support for starlette, FastAPI, sanic
- [x] Investigate async support for Django 3.0

**Comment by beniwohli** [comment]
Closing this, as general asyncio support has been implemented
