### ISSUE TITLE
[meta][docs] Documentation restructure

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-python#616]
A meta issue for tracking documentation improvements outlined in https://github.com/elastic/apm-dev/issues/425.

### Doc restructure
- [x] master - https://github.com/elastic/apm-agent-python/pull/617

### Build release notes to docs: 
More details: https://github.com/elastic/apm/issues/132.
The PRs in each group must be merged at the same time to prevent breaking the doc build.

#### `master`
- [x] apm-agent-python - https://github.com/elastic/apm-agent-python/pull/619
- [x] docs - https://github.com/elastic/docs/pull/1350

#### `5.x`
- [x] docs pr - https://github.com/elastic/docs/pull/1351
